### ISSUE TITLE
How to run this on Ubuntu 20?

### ISSUE THREAD

**Issue by jaum20** [cantalupo555/qbittorrent-backup-linux#2]
I am on ubtuntu 20 and can't run this since there is no plocate package to ubuntu 20

**Comment by cantalupo555** [comment]
If you use ubuntu you can remove these lines.

```

elif [ ! -f /usr/bin/mlocate ]; then
	echo -e "\n\033[1;31mPlease install the 'mlocate' package.\033[0m"
	echo "sudo apt install mlocate"
	exit 1
elif [ ! -f /usr/bin/plocate ]; then
	echo -e "\n\033[1;31mPlease install the 'plocate' package.\033[0m"
	echo "sudo apt install plocate"
	exit 1
```

I will update the script soon, the current state will have confusion for Linux beginners.
I plan to add flatpak support as well.

**Comment by jaum20** [comment]
Thank you
